repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 1.34.1
    hooks:
      - id: djlint
        name: djLint (Jinja)
        entry: djlint --profile=jinja --reformat --check
        language: python
        types: [jinja]
        files: templates/.*\.jinja$

# Node.js static asset hooks
- repo: local
  hooks:
    - id: prettier-static
      name: Prettier (static js/css)
      entry: npm run prettier --
      language: system
      types: [css, js]
      files: static/(js|css)/.*\.(js|css)$
    - id: eslint-static
      name: ESLint (static js)
      entry: npm run lint:js --
      language: system
      types: [js]
      files: static/js/.*\.js$
    - id: stylelint-static
      name: Stylelint (static css)
      entry: npm run lint:css --
      language: system
      types: [css]
      files: static/css/.*\.css$
