blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/thezak48/comps/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/thezak48/comps/wiki
    about: Check our documentation first
