version: "3.8"

services:
  image-comparison:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: comps
    ports:
      - "8000:8000"
    environment:
      - PUID=1000
      - PGID=1000
      - DB_PATH=/config/comparisons.db
      - UPLOADS_PATH=/data/uploads
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
